### ISSUE TITLE
输入账号和密码运行报错。

### ISSUE THREAD

**Issue by PLA888** [VermiIIi0n/fuckZHS#1]
usage: ZHS Fucker [-h] -c COURSE [-v VIDEOS [VIDEOS ...]] [-u USERNAME] [-p PASSWORD] [-s SPEED]
                  [-t THRESHOLD] [--webdriver WEBDRIVER]
ZHS Fucker: error: the following arguments are required: -c/--course

**Comment by VermiIIi0n** [comment]
"-c"是课程ID，是必须的参数，可以从课程网页的URL中获得。报错信息已经说了你缺少参数了，具体说明和更多选项用 "python main.py -h" 查看吧
