### ISSUE TITLE
[BUG]扫码后提示：该网站的安全证书存在问题，可选择“继续”在浏览器中访问。

### ISSUE THREAD

**Issue by Lbt777** [VermiIIi0n/fuckZHS#101]
**描述问题**
请详细清晰地描述问题
微信扫码后提示证书存在问题 只能通过浏览器打开
控制台无报错
**如何复现**
您遇到问题前进行了什么操作:
1. 执行python main.py 后微信扫码
2. 扫码后提示证书存在问题
3. 无法登录

**截图**
如果可以的话，请附上截图.
![b3f1374c19bb72f6df35c070aeed5d6](https://github.com/user-attachments/assets/5c6850e6-9456-409a-9130-2bca5c95ad95)
![image](https://github.com/user-attachments/assets/6945adb6-1563-44e2-8a65-656e9f7e3161)
![image](https://github.com/user-attachments/assets/af601350-afaf-4ead-8941-4206af7286eb)

**您的操作系统和所使用的本代码版本**
 - OS: [e.g. stupid Windows] Windows
 - Version: [e.g. 2.0.2] Python 3.13.0
"config_version": "1.4.0"
**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
最好有 DEBUG 级别日志(使用参数 `-d` 或在配置文件中更改日志等级)

**Comment by VermiIIi0n** [comment]
这要使用知到App扫描，不能使用微信
