### ISSUE TITLE
[BUG]怎么安装pip安装依赖啊 纯小白

### ISSUE THREAD

**Issue by Trout1117** [VermiIIi0n/fuckZHS#108]
![屏幕截图 2024-11-17 220651](https://github.com/user-attachments/assets/6330488e-8310-4fc1-8b23-3a5c649c4879)

**Comment by Trout1117** [comment]
![Uploading 屏幕截图 2024-11-17 221004.png…]()

**Comment by Trout1117** [comment]
![Uploading 屏幕截图 2024-11-17 221004.png…]()

**Comment by Trout1117** [comment]
以及怎么Ultra Quick Start: 执行 python main.py？还是因为安装依赖没好所以不行？

**Comment by Trout1117** [comment]
idle没反应，pycharm显示  D:\python\python.exe "D:\fuckZHS-2.6.1 (1)\fuckZHS-2.6.1\main.py" 
Traceback (most recent call last):
  File "D:\fuckZHS-2.6.1 (1)\fuckZHS-2.6.1\main.py", line 9, in <module>
    from fucker import Fucker
  File "D:\fuckZHS-2.6.1 (1)\fuckZHS-2.6.1\fucker.py", line 2, in <module>
    from utils import progressBar, HMS, wipeLine, list_to_cookie_jar
  File "D:\fuckZHS-2.6.1 (1)\fuckZHS-2.6.1\utils.py", line 97, in <module>
    length = (os.get_terminal_size().columns-4), fill = '#'):
              ~~~~~~~~~~~~~~~~~~~~^^
OSError: [WinError 6] 句柄无效。

**Comment by an12138884** [comment]
请问您是怎么解决的，我也是纯小白，只是想刷个课来着卡在这里了😭

**Comment by Trout1117** [comment]
> 请问您是怎么解决的，我也是纯小白，只是想刷个课来着卡在这里了😭

将requirement安装到c盘的用户文件夹中再使用cmd安装依赖，应该？后续该怎么运行mainpython呢，至今不解

**Comment by VermiIIi0n** [comment]
> idle没反应，pycharm显示 D:\python\python.exe "D:\fuckZHS-2.6.1 (1)\fuckZHS-2.6.1\main.py" Traceback (most recent call last): File "D:\fuckZHS-2.6.1 (1)\fuckZHS-2.6.1\main.py", line 9, in from fucker import Fucker File "D:\fuckZHS-2.6.1 (1)\fuckZHS-2.6.1\fucker.py", line 2, in from utils import progressBar, HMS, wipeLine, list_to_cookie_jar File "D:\fuckZHS-2.6.1 (1)\fuckZHS-2.6.1\utils.py", line 97, in length = (os.get_terminal_size().columns-4), fill = '#'): ~~~~~~~~~~~~~~~~~~~~^^ OSError: [WinError 6] 句柄无效。

PyCharm 在老版本里有问题, 直接 clone 或者打包下载这个 repo 最新版就行, 或者不要使用 PyCharm 运行.

这类问题可以善用GPT, 解答更快速

**Comment by NWPU-huy** [comment]
> > 请问您是怎么解决的，我也是纯小白，只是想刷个课来着卡在这里了😭
> 
> 将requirement安装到c盘的用户文件夹中再使用cmd安装依赖，应该？后续该怎么运行mainpython呢，至今不解

这个是因为你需要在项目的文件夹中安装这个依赖，因为这里pip安装的时候，识别的是相对路径，也就是说只有跟你这个文件夹同级别的文件能识别到。所以你最开始的报错说文件没有找到。
后续如果要运行py文件的话就找个python编辑工具，比如vscode或者是pycharm，然后运行就行。或者如果是你已经在电脑上安装了python，但是没有安装编辑器，也可以直接在那个文件夹中打开终端，然后输入python main.py -c 114551这样运行这个python文件（注意这里跟上面一样，仍然是相对路径，所以需要在文件夹中打开）
**如果你要安装vscode，建议你在B站找个教程，否则你根本不会运行这个文件**
