### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by windsup516** [VermiIIi0n/fuckZHS#112]
**描述问题**
我是个小白。现在这个界面是正在刷课了吗

**如何复现**
您遇到问题前进行了什么操作:
登录了

1. 这样
2. 那样
3. 这里
4. 那里

**截图**
![image](https://github.com/user-attachments/assets/1bc0f20e-36f0-4e53-ae08-7fe5504ec52b)

**您的操作系统和所使用的本代码版本**
 - OS: [e.g. stupid Windows]
 - Version: [e.g. 2.0.2]

**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
最好有 DEBUG 级别日志(使用参数 `-d` 或在配置文件中更改日志等级)

**Comment by 7M7666** [comment]
shide
