### ISSUE TITLE
[BUG]SSL证书错误

### ISSUE THREAD

**Issue by douminik** [VermiIIi0n/fuckZHS#12]
Scan QR code
QR login failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
报错信息如上

**Comment by VermiIIi0n** [comment]
https://github.com/VermiIIi0n/fuckZHS#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by douminik** [comment]
我没开代理 也尝试在config中改     "proxies":{"https":""}, 也无效 另外 我是mac系统

**Comment by VermiIIi0n** [comment]
我也是mac, 刚测试了没问题. 证书问题不归我这脚本管, 要不是 Python 的锅, 要不是系统证书配置的锅. 

实在不行可以无视证书, 不过会报一大堆警告.

**Comment by douminik** [comment]
管理证书的在哪个文件呢我去修改

**Comment by douminik** [comment]
应该是python的锅我用的python3.10 错误在一个ssl.py文件

**Comment by VermiIIi0n** [comment]
> 管理证书的在哪个文件呢我去修改

我也不知道是什么问题导致的, 也没法告诉你怎么做.
总之先更新下 Python 自己的证书吧..

运行 `pip install -U certifi` 后再试试吧

**Comment by douminik** [comment]
还是不行，是否可以在下个版本进行手动添加cookie的方式登录

**Comment by VermiIIi0n** [comment]
> 还是不行，是否可以在下个版本进行手动添加cookie的方式登录

可以, 但是智慧树Cookies过期太快了

目前版本也可以直接改 main.py

```Python
### create an instance, now we are talking... or fucking
fucker = Fucker(proxies=proxies, speed=args.speed, end_thre=args.threshold, limit=args.limit)

### first you need to login to get cookies
try:
    if qrlogin:
        callback = partial(showImage, show_in_terminal=show_in_terminal ,char_width=qr_char_width, ensure_unicode=qr_ensure_unicode)
        fucker.login(use_qr=True, qr_callback=callback)
    else:
         fucker.login(username, password)
    print("Login Successful\n")
except Exception as e:
    print(e)
    exit(1)
```
->
```Python
fucker = Fucker(proxies=proxies, speed=args.speed, end_thre=args.threshold, limit=args.limit)
fucker.cookies = {}  # Your cookies
```
