### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by candongzuilishang** [VermiIIi0n/fuckZHS#13]
**描述问题**
如何使用账号密码登陆，关闭二维码登陆后还是默认使用二维码

**如何复现**
您遇到问题前进行了什么操作:
1. 这样
2. 那样
3. 这里
4. 那里

**截图**
如果可以的话，请附上截图.

**您的操作系统和所使用的本代码版本**
 - OS: [e.g. stupid Windows]
 - Version: [e.g. 2.0.2]

**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
最好有 DEBUG 级别日志(使用参数 `-d` 或在配置文件中更改日志等级)

**Comment by VermiIIi0n** [comment]
因为登录验证改变目前密码登陆是失效的，请先阅读文档🫠
