### ISSUE TITLE
[BUG]二维码过期

### ISSUE THREAD

**Issue by qimiaoi** [VermiIIi0n/fuckZHS#14]
生成二维码立马用手机app扫显示二维码过期，已经试了好几次了

**Comment by DigelHost** [comment]
换用linux环境解决

**Comment by qimiaoi** [comment]
> 

大佬能教教我嘛，搞了半天也没搞好

**Comment by VermiIIi0n** [comment]
前两星期被智障防疫搞去隔离了，回复晚了不好意思，不知道你有没有解决了。

总之这个脚本基本没在了色 Windows 上测试过，你可以在微软商店里下载 Ubuntu 子系统，用那个跑就行。

> 生成二维码立马用手机app扫显示二维码过期，已经试了好几次了

**Comment by qimiaoi** [comment]
> 



好的，谢谢大佬，我再试一下。

**Comment by qimiaoi** [comment]
> 前两星期被智障防疫搞去隔离了，回复晚了不好意思，不知道你有没有解决了。
> 
> 总之这个脚本基本没在了色 Windows 上测试过，你可以在微软商店里下载 Ubuntu 子系统，用那个跑就行。
> 好的，谢谢大佬，我再试一下，前两天再Linux系统上试给我搞迷糊了

**Comment by VermiIIi0n** [comment]
我从没碰到过这个问题...有可能是IP不够干净？如果有挂代理的话关掉看看吧...

**Comment by qimiaoi** [comment]
> 我从没碰到过这个问题...有可能是IP不够干净？如果有挂代理的话关掉看看吧...

大佬，代理也关了，还是不行，害，我卡这了

**Comment by VermiIIi0n** [comment]
那就放弃 Win 吧... 用 Linux 是遇到了什么问题呢? 装完依赖应该可以直接运行了啊?

**Comment by YoumyTheGoust** [comment]
为啥我在服务器上跑的时候，知到app识别不到那个二维码？

**Comment by YoumyTheGoust** [comment]
为啥我在服务器上跑的时候，弹出的登录二维码知到app识别不出来？

**Comment by VermiIIi0n** [comment]
貌似有些机型是要难识别一点，也跟你使用的字体和终端行间距之类的东西有关，最近两天我改进下二维码吧，现在的这个缺点挺多。

暂时先试试不同角度拍摄，用透视修正下变形的二维码。

**Comment by VermiIIi0n** [comment]
> 为啥我在服务器上跑的时候，弹出的登录二维码知到app识别不出来？

小幅度更新了下二维码, 最外层加了个边框, 现在再试试?

**Comment by VermiIIi0n** [comment]
> 会不会是因为智慧树码是黑色白底，咱们这个码是白色黑底的原因？

和黑白底倒没啥关系, 主要是 Android 端上不知道知到用的什么垃圾二维码识别库, iOS 上是没问题的.

再试试把 config.json 里的 ensure_unicode 改成 true 试试吧? 说不定就能用了

**Comment by YoumyTheGoust** [comment]
> > 会不会是因为智慧树码是黑色白底，咱们这个码是白色黑底的原因？
> 
> 和黑白底倒没啥关系, 主要是 Android 端上不知道知到用的什么垃圾二维码识别库, iOS 上是没问题的.
> 
> 再试试把 config.json 里的 ensure_unicode 改成 true 试试吧? 说不定就能用了

刚刚测试过了，把终端输出的二维码截图然后去ps上修改了一下反色，改为白底黑色二维码就能识别出来了T^T

**Comment by VermiIIi0n** [comment]
绝了, 那可能安卓上是他们自己写的垃圾二维码识别代码吧...

总之我现在改改, 当时脑抽了搞成黑底以适应我的终端样式, 看来翻车了.

感谢反馈~

**Comment by VermiIIi0n** [comment]
> > 我从没碰到过这个问题...有可能是IP不够干净？如果有挂代理的话关掉看看吧...
> 
> 大佬，代理也关了，还是不行，害，我卡这了

Halo, 前来更新下这个 issue, 基本上确定是 Windows 下 PIL 的 tempfile 有问题了.

下个版本试着修复, 目前版本更新 v2.3.6 之后应该就默认打印到终端, 避开了出问题的代码, 你再试试?
