### ISSUE TITLE
需要弹出滑块验证

### ISSUE THREAD

**Issue by YoumyTheGoust** [VermiIIi0n/fuckZHS#17]
执行的时候显示课程“需要弹出滑块验证”
登录账号后发现，观看视频前弹出了一个点击对应字母/数字的验证。这个有办法吗？
![image](https://user-images.githubusercontent.com/63649572/194311608-c0800912-89d9-4f42-a827-1f5511d4680b.png)

**Comment by VermiIIi0n** [comment]
这个得先手动登录网页版然后过验证, 在常见事项里有写
