### ISSUE TITLE
网址里只有 recruitCourseId, 没有 courseId

### ISSUE THREAD

**Issue by 1485773425** [VermiIIi0n/fuckZHS#2]
求解

**Comment by VermiIIi0n** [comment]
什么信息都没提供，我也帮不到你啊

**Comment by PlumPlum-FISH** [comment]
> 什么信息都没提供，我也帮不到你啊

你吼，现在网址那里的CourseId变成一串数字字母混淆了，大佬有无办法破掉😭(举例recruitAndCourseId=4b595a5b4d5c4859454a5859584d584659)

**Comment by VermiIIi0n** [comment]
氦, 感谢反馈~ 

我看了看发现这坨智慧树有两套API. 我的必修课程都是域名开头为hike.zhihuishu.com的API, 而你的应该是studyservice-api.zhihuishu.com开头的版本. 这俩版本差距挺大的. 最近还有期末作业, 可能得花点时间才能搞定你的那套, 弄好了我会回复你的👍.

**Comment by PlumPlum-FISH** [comment]
> 氦, 感谢反馈~
> 
> 我看了看发现这坨智慧树有两套API. 我的必修课程都是域名开头为hike.zhihuishu.com的API, 而你的应该是studyservice-api.zhihuishu.com开头的版本. 这俩版本差距挺大的. 最近还有期末作业, 可能得花点时间才能搞定你的那套, 弄好了我会回复你的👍.

谢谢，不着急 大佬忙完再弄都可以的 万分感谢🥲

**Comment by VermiIIi0n** [comment]
改好了, 麻烦看看能用不...我能上的课太少了可能会有些没发现的问题
还有就是这次大改了许多东西, README里写了重要的注意事项, 请多注意

**Comment by stubborn-fk** [comment]
作者大大，请问用户名是啥啊 学号或者手机号都可以吗 login失败

**Comment by VermiIIi0n** [comment]
> 

请问有报错信息吗...我只用手机号测试过, 看源码的话邮箱和电话都可以, 学号没测试过. 看登陆API的话应该用哪个都一样

**Comment by stubborn-fk** [comment]
不太懂啊，我是萌新 装完那两个包之后直接在vscode里运行了main.py 或许我的操作有问题？终端抛出了好几个异常
![image](https://user-images.githubusercontent.com/98369312/168462049-b93f1dea-5a53-400b-a4e0-cc48b6ba1360.png)
![image](https://user-images.githubusercontent.com/98369312/168462071-820df0a7-af92-48fe-97d0-f9ab570a4fbf.png)
![image](https://user-images.githubusercontent.com/98369312/168462083-6e682b9a-34eb-46bd-9e99-4cc5d833f8ee.png)
![image](https://user-images.githubusercontent.com/98369312/168462143-a003bb8f-402e-4c00-b1b1-09cdec3e738f.png)
还有一大段......
最后一个异常提示登录失败
![image](https://user-images.githubusercontent.com/98369312/168462181-03361d98-4b17-48fa-b38d-4faf610f914f.png)
大佬能帮看一眼吗

**Comment by VermiIIi0n** [comment]
我在Windows上试了一下, 如果开着Clash之类的代理就会出这个证书错误异常, 先试着把代理关掉看看吧. 🌚👍🏿

**Comment by stubborn-fk** [comment]
好家伙，原来是这样 我还真开着clash...

**Comment by stubborn-fk** [comment]
只需要等他慢慢fucking就行吧

**Comment by VermiIIi0n** [comment]
氦, 是这样的, 建议不要过度操劳身体, 一次十来分钟就行, 不然容易弹人机验证

然后那个证书错误是urllib的锅, Windows上把Clash配置成TUN模式, 然后关系统代理选项就可以不影响上网又能刷课了. 我之后看看咋修吧
我没在Win上测试过这个脚本, 似乎除了证书问题, PowerShell显示中文也有些问题...

**Comment by stubborn-fk** [comment]
奥奥奥 懂了 谢谢大佬 膜👍

**Comment by stubborn-fk** [comment]
fuck了一会(30min左右)用网页打开找不到视频了 （但是python终端依然可以fuck）是被检测了吗
![image](https://user-images.githubusercontent.com/98369312/168464955-96bdec6c-8388-4871-bb66-b99582b62d34.png)

**Comment by stubborn-fk** [comment]
重新登陆又好了

**Comment by VermiIIi0n** [comment]
一次只能在一个地方登陆, 是Python把你浏览器挤下线了, 反过来也可以, 说明fxxking时不要分心 (

**Comment by stubborn-fk** [comment]
哈哈哈 好的
