### ISSUE TITLE
[BUG]无法生成二维码

### ISSUE THREAD

**Issue by Hyx0907** [VermiIIi0n/fuckZHS#22]
**描述问题**
打开main之后无法生成二维码

**如何复现**
您遇到问题前进行了什么操作:
1. 打开main.py
2. 程序页面出现一堆重复乱码，不显示二维码

**截图**
![PNG图像](https://user-images.githubusercontent.com/115090179/194559702-1137a1ac-5c03-4006-a555-95d3b2417fec.png)

**您的操作系统和所使用的本代码版本**
 - OS: windows 11
 - Version: 2.3.4

**错误日志**
……日志是啥？

**Comment by VermiIIi0n** [comment]
啊，cmd不支持这几个字符， 要不换成 PowerShell 运行，或在 config.json 里开启 ensure unicode，再或者在 config.json里关闭 show in terminal。

三种方法任选一个吧～

**Comment by Hyx0907** [comment]
能显示了，谢谢大佬🤝🤝🤝

**Comment by oobo4** [comment]
好了谢谢

**Comment by zxz1314258** [comment]
![Uploading image.png…]()
就是我设置了密码登录还是返回二维码

**Comment by zxz1314258** [comment]
[https://pic.imgdb.cn/item/6492b96a1ddac507cce95a5b.png](url)
1.我设置的二维码禁用，用的密码登录，但还是返回二维码
2.我用二维码扫描，这二维码确是无效，扫了没有反应，测试了很多遍，都是这样
求救

**Comment by zxz1314258** [comment]
[](https://pic.imgdb.cn/item/6492b96a1ddac507cce95a5b.png)

**Comment by VermiIIi0n** [comment]
阁下这字体不适合显示二维码, 有几种办法, 可以在设置里以图片显示, 也可以换个终端字体, 又或者物理透视(从上或下斜着拍)
