### ISSUE TITLE
[BUG] 关于windows平台下二维码问题的解决(应该

### ISSUE THREAD

**Issue by DigelHost** [VermiIIi0n/fuckZHS#23]
破案了.......
在 utils.py 中 showImage 函数存在问题
![image](https://user-images.githubusercontent.com/54343333/194577170-ce70bdba-714d-45df-b28f-8ac17efc6a25.png)
 "img.show()"这条语句似乎不能正常结束
在调试过程中，我在此语句断点并跳过后正常登录
~~我没有使用过这些库，因此我无法提供更多帮助~~

原因似乎在于img.show() 此语句要等待 图片进程结束才能继续下面的语句，在扫码之后关闭图片进程的数秒后再次点击登录即可正常运行

**Comment by DigelHost** [comment]
貌似不是很难修，直接base64decode然后写入一个图片，然后再调用os库中某个函数打开(应该把

**Comment by VermiIIi0n** [comment]
谢谢反馈~

看起来你用的是 v2.3.4, 试试最新版吧. 新版默认会二维码打印到终端, 避开了 `img.show()`, 但得用 PowerShell 运行.

**Comment by VermiIIi0n** [comment]
似乎其他人在 Windows 上遇到的问题多是二维码过期... 只能说 Windows 真的拉.

想请问下你有遇到类似的二维码过期的问题吗? 没法复现这问题, 搞得头大.🥲

**Comment by DigelHost** [comment]
二维码过期的话问题应该在websocket连接上，websocket没连接会提示二维码过期,二维码生成方面出现的问题倒没遇见过。按理来说修改terminal输出二维码不存在登录问题

**Comment by VermiIIi0n** [comment]
哦哦, 我还以为是 tempfile 出了问题, 没考虑到是 show() 阻断了后面的 WS 连接. 

说起来 os 里没什么能打开图片的函数, 直接用命令行又依赖于系统... 干脆把 show() 扔单独一个线程里跑吧.

把 showImage 的 else 后面那段替换成这个试试? 抓个壮丁测试一下, 能帮忙的话就太好了🙏
```Python
import threading
img = Image.open(io.BytesIO(img))
threading.Thread(target=img.show).run()
```

没问题的话下次更新里改成这个.

**Comment by DigelHost** [comment]
emm,我在stackoverflow找到这个问题的一些帮助
[https://stackoverflow.com/questions/13327759/how-do-i-display-and-close-an-image-with-python](url)

**Comment by DigelHost** [comment]
![image](https://user-images.githubusercontent.com/54343333/194706686-23b22b2b-3267-4065-a224-f03e8d2b0eb8.png)
试了试，不知道是不是我的问题，效果不是很好
`print("Scan QR code")` 并没有执行

**Comment by VermiIIi0n** [comment]
> emm,我在stackoverflow找到这个问题的一些帮助 [https://stackoverflow.com/questions/13327759/how-do-i-display-and-close-an-image-with-python](url) 也许matplotlib是个更好的选择

哈哈, 感觉那样有些小题大做了

*******


> ![image](https://user-images.githubusercontent.com/54343333/194706686-23b22b2b-3267-4065-a224-f03e8d2b0eb8.png) 试了试，不知道是不是我的问题，效果不是很好 `print("Scan QR code")` 并没有执行

不会吧, 单独线程里跑都还能阻断, 这也太不合理了.

我刚也找了台 Win 试了一下, 运行没问题. 不过确实有段一秒左右的延时才出现 Scan QR code, 之后正常登陆.

**Comment by DigelHost** [comment]
也许是我的问题

**Comment by VermiIIi0n** [comment]
> 

你的问题就是我的问题(

说实话因为我这台 Win 原本就没有问题, 所以我也不知道现在到底修好没🫠

**Comment by VermiIIi0n** [comment]
看样子应该大概也许可能是修好了罢.

谢谢帮助~
