### ISSUE TITLE
二维码过期

### ISSUE THREAD

**Issue by qimiaoi** [VermiIIi0n/fuckZHS#26]
> > 我从没碰到过这个问题...有可能是IP不够干净？如果有挂代理的话关掉看看吧...
> 
> 大佬，代理也关了，还是不行，害，我卡这了

Halo, 前来更新下这个 issue, 基本上确定是 Windows 下 PIL 的 tempfile 有问题了.

下个版本试着修复, 目前版本更新 v2.3.6 之后应该就默认打印到终端, 避开了出问题的代码, 你再试试?
大佬，还是二维码过期，刚刚试的，我这个小白不会用Linux，麻烦大佬了

_Originally posted by @VermiIIi0n in https://github.com/VermiIIi0n/fuckZHS/issues/14#issuecomment-1272211750_

**Comment by VermiIIi0n** [comment]
为什么新开了个issue呢😂

意思现在打印到终端的二维码也还是过期？

**Comment by qimiaoi** [comment]
> 什么新开了个issue

不好意思大佬，点错了，咦我打开运行main.py,怎么没在终端生成二维码，又弹窗生成的，我也刚刚重新又下载了码源哈

**Comment by qimiaoi** [comment]
> 为什么新开了个issue呢😂
> 
> 意思像这样打印到终端的二维码也还是过期？ <img alt="image" width="821" src="https://user-images.githubusercontent.com/104612478/194701238-4155b988-b280-4fe9-87ad-6a3ea5
![屏幕截图 2022-10-08 195752](https://user-images.githubusercontent.com/94031439/194706326-108c41af-1e0a-44d2-8858-b1059977cd6c.png)
7c0975.png">
大佬，这个是最新的嘛

**Comment by qimiaoi** [comment]
> > 什么新开了个issue
> 
> 不好意思大佬，点错了，咦我打开运行 main.py，怎么没在终端生成二维码，又弹窗生成的，我也刚刚重新又下载了码源哈

大佬这个是最新的嘛
![屏幕截图 2022-10-08 195752](https://user-images.githubusercontent.com/94031439/194706385-a7faef23-a41d-4acd-a96b-b16b198a28cd.png)

**Comment by VermiIIi0n** [comment]
直接 clone 的话就是最新版了, 下下来的 meta.json 里的版本应该是 2.3.6.

我不知道为什么你的配置文件没被自动更新, 不过手动改也可以, 将 config.json 里的 show in terminal 值改成 true 就可以打印到终端了.

如果愿意等的话, 下个版本应该能修复这个过期问题~

**Comment by qimiaoi** [comment]
> 直接 clone 的话就是最新版了, 下下来的 meta.json 里的版本应该是 2.3.6.
> 
> 我不知道为什么你的配置文件没被自动更新, 不过手动改也可以, 将 config.json 里的 show in terminal 值改成 true 就可以打印到终端了.
> 
> 如果愿意等的话, 下个版本应该能修复这个过期问题~

感谢大佬，终于好了，完美运行
