### ISSUE TITLE
[BUG] 课下部分视频无法刷

### ISSUE THREAD

**Issue by Tracker647** [VermiIIi0n/fuckZHS#27]
**描述问题**
无法刷进度的视频下面会显示
|##Failed: questionPoint not found in {'videoThemeDtos': None, 'popupPictureDtos': [], 'knowledgeCardDtos': None}
**截图**
![image](https://user-images.githubusercontent.com/54085641/195045985-19591308-5728-48c2-9dc3-7bb1b785ab96.png)

**您的操作系统和所使用的本代码版本**
 - OS: Ubuntu虚拟机
 - Version: 20.04 LTS

**Comment by VermiIIi0n** [comment]
谢谢反馈, 麻烦替换下文件看看正常没有, 没问题的话之后更新.
[fucker.py.zip](https://github.com/VermiIIi0n/fuckZHS/files/9754896/fucker.py.zip)

**Comment by Tracker647** [comment]
> 谢谢反馈, 麻烦替换下文件看看正常没有, 没问题的话之后更新. [fucker.py.zip](https://github.com/VermiIIi0n/fuckZHS/files/9754896/fucker.py.zip)

ok，能正常刷了，thx
