### ISSUE TITLE
[BUG] QR login failed

### ISSUE THREAD

**Issue by 2682856025** [VermiIIi0n/fuckZHS#29]
Macos系统 pycharm运行
刚运行就报错
![Uploading AEB1A712-F7FA-47E2-9A66-0625CE23C5C8.png…]()

**Comment by 2682856025** [comment]
![Uploading 979B8ADA-DA85-4B03-A4ED-F9EFC2BF3DCF.png…]()

**Comment by VermiIIi0n** [comment]
你上传的图片我看不到. 然后请按 issue 模版填写内容, 不然信息不足我也帮不上你.

**Comment by VermiIIi0n** [comment]
才发现你开了另一个 issue, 那既然是一样的问题, 我就把这个关闭了咯. 

顺便一提因为没法复现问题, 我也没找着什么有效的办法...
