### ISSUE TITLE
uuid not found in {'phone': '178****2831', 'status': -9}

### ISSUE THREAD

**Issue by YCCDSZXH** [VermiIIi0n/fuckZHS#3]
**描述问题**
输入账号和密码后会出现这个
![image](https://user-images.githubusercontent.com/94218957/168967426-28fa5bc6-b567-4eb9-926f-8bd1497a2f2f.png)
账号和密码都是正确的.

**如何复现**
登录账号就会出现这个问题
我看 js 发现是一个 ajax 请求, 用 python 返回的结果和 ajax 拿到的不一样

**截图**
![image](https://user-images.githubusercontent.com/94218957/168967976-ce5c80a6-fd58-464c-b904-6c5b740cd2b9.png)
这个url 有点问题
**您的操作系统和所使用的本代码版本**
操作系统是 Linux,
Python 3.10.4,
代码是    "version": "2.2.1",

**错误日志**
没有 debug 日志,只有 error 的日志

2022-05-18 13:55:14,033:  uuid not found in {'phone': '178****2831', 'status': -9}
Traceback (most recent call last):
  File "/home/ubuntu/Git/fuckZHS/ObjDict.py", line 97, in __getattr__
    return self[name]
  File "/home/ubuntu/Git/fuckZHS/ObjDict.py", line 121, in __getitem__
    raise KeyError(f"{name} not found in {self}")
KeyError: "uuid not found in {'phone': '178****2831', 'status': -9}"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Git/fuckZHS/fucker.py", line 134, in login
    need_auth = self._apiQuery(check_url, {"uuid": user_info.uuid}).rt.needAuth
  File "/home/ubuntu/Git/fuckZHS/ObjDict.py", line 101, in __getattr__
    raise AttributeError(f"{name} not found in {self}")
AttributeError: uuid not found in {'phone': '178****2831', 'status': -9}

**Comment by VermiIIi0n** [comment]
登陆成功的 status 应该是 1, 应该是账号密码错了, 输错的时候才会返回-9

**Comment by VermiIIi0n** [comment]
氦, 我实在没法复现这个问题, 只能麻烦你发下DEBUG日志了🥲

**Comment by YCCDSZXH** [comment]
问题解决了, 我在本地运行没有问题,
出问题是因为我是在tencent 服务器上跑的,估计是 ZHS 把 ip 列为了黑名单,
在本地跑完全没问题, 
打扰大佬了

**Comment by VermiIIi0n** [comment]
啊, 没事, 顺带一说他们的防火墙挡IP的报错和这个不太一样, 你也有可能是遇到异地登录的检测了🌚, 毕竟返回了个电话号
