### ISSUE TITLE
不能运行 地一排显示  *Failed to check update

### ISSUE THREAD

**Issue by oobo4** [VermiIIi0n/fuckZHS#30]
**描述问题**
请详细清晰地描述问题

**如何复现**
您遇到问题前进行了什么操作:
1. 这样
2. 那样
3. 这里
4. 那里

**截图**
如果可以的话，请附上截图.

**您的操作系统和所使用的本代码版本**
 - OS: [e.g. stupid Windows]
 - Version: [e.g. 2.0.2]

**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
最好有 DEBUG 级别日志(使用参数 `-d` 或在配置文件中更改日志等级)

**Comment by oobo4** [comment]
![Uploading 捕获.PNG…]()
这是中间和结尾

**Comment by VermiIIi0n** [comment]
更新检查不影响正常刷课.

信息不足没法帮你, 至少把 issue 模版内容填上.

**Comment by oobo4** [comment]
![捕获](https://user-images.githubusercontent.com/102136608/195501549-cdb4617d-02c7-4062-ba5f-2890cf8c215d.PNG)
![11](https://user-images.githubusercontent.com/102136608/195501634-772205b4-61c8-497f-b1de-bb0721fbddf4.PNG)
是这样的

**Comment by DigelHost** [comment]
https://github.com/VermiIIi0n/fuckZHS/issues/22
