### ISSUE TITLE
登录二维码不弹出了

### ISSUE THREAD

**Issue by abai2020** [VermiIIi0n/fuckZHS#32]
显示一些如下的代码
[0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0m
[0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;47m  [0;37;40m  [0;37;47m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;40m  [0;37;47m  [0;37;47m  [0;37;47m  [0m
[0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0m
[0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0;37;47m  [0m

**Comment by VermiIIi0n** [comment]
#22 

我之后把这问题加到 #25 吧

**Comment by abai2020** [comment]
好的
