### ISSUE TITLE
main.py", line 78 SyntaxError: invalid syntax [BUG]

### ISSUE THREAD

**Issue by Vc-li** [VermiIIi0n/fuckZHS#34]
**描述问题**
执行 python3 main.py 时出现报错

**如何复现**
您遇到问题前进行了什么操作:
1. 这样
2. 那样
3. 这里
4. 那里

**截图**
<img width="588" alt="image" src="https://user-images.githubusercontent.com/77320315/199771096-93f7ec67-7544-4604-ae20-243e5da2ae23.png">
<img width="651" alt="image" src="https://user-images.githubusercontent.com/77320315/199771115-ebbd1f43-5c91-42ed-bb3b-4b9f48d457bb.png">

**您的操作系统和所使用的本代码版本**
 - OS: Debain
 - Version: 2.3.8

**错误日志**
<img width="545" alt="image" src="https://user-images.githubusercontent.com/77320315/199771439-e028e515-ea07-437b-a39e-11c4e12b1282.png">

**Comment by Vc-li** [comment]
用pycharm打开这一块也是报错的，不知道谁不是我环境版本有问题
<img width="597" alt="image" src="https://user-images.githubusercontent.com/77320315/199773074-ce78c72d-f10c-4d84-99c6-79f20420fb72.png">

**Comment by Vc-li** [comment]
python3.10
<img width="817" alt="image" src="https://user-images.githubusercontent.com/77320315/199783047-3d9fe195-1da8-45ef-872e-d021a4ae9b3c.png">

**Comment by VermiIIi0n** [comment]
> python3.10 <img alt="image" width="817" src="https://user-images.githubusercontent.com/77320315/199783047-3d9fe195-1da8-45ef-872e-d021a4ae9b3c.png">

这么多依赖没安装? 你有运行 `pip install -r requirements.txt` 吗?

语法报错那个记得把环境改成 Python3.10+ 就行

**Comment by Vc-li** [comment]
> > python3.10 <img alt="image" width="817" src="https://user-images.githubusercontent.com/77320315/199783047-3d9fe195-1da8-45ef-872e-d021a4ae9b3c.png">
> 
> 这么多依赖没安装? 你有运行 `pip install -r requirements.txt` 吗?
> 
> 语法报错那个记得把环境改成 Python3.10+ 就行

依赖安装过了呀，不知道啥情况
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/77320315/199870819-437f64b6-c61f-4f3d-9f0c-249901ce0a65.png">

**Comment by VermiIIi0n** [comment]
按理说装 `pycryptodome` 的时候 `cffi` `ctypes` 也会一起装, 现在手动 `pip install cffi ctypes` 装下试试吧?
反正缺啥装啥就行.

**Comment by Vc-li** [comment]
> 按理说装 `pycryptodome` 的时候 `cffi` `ctypes` 也会一起装, 现在手动 `pip install cffi ctypes` 装下试试吧? 反正缺啥装啥就行.

感谢，搞定了🤝
