### ISSUE TITLE
fucker.cookies具体输入使用

### ISSUE THREAD

**Issue by Jikexiaobai** [VermiIIi0n/fuckZHS#35]
麻烦问一下，在视频页面接口里拿到的cookies，粘贴在fucker.cookies 后面什么位置，方便具体说说吗

**Comment by VermiIIi0n** [comment]
直接赋值给属性就可以

```
fucker.cookies = {}
```

顺便一提这样会自动提取用户的 uuid, 所以赋值不合法的 cookies 会引发异常

**Comment by Jikexiaobai** [comment]
顺便请问一下，大佬是否有修复帐密登陆的计划😘

**Comment by VermiIIi0n** [comment]
> 顺便请问一下，大佬是否有修复帐密登陆的计划😘

曾有两方案但目前都咕咕了
* ML 大法: 为了这几十K的脚本搞几百兆的模型太离谱, 想想算了
* 逆向安卓 知到APP: 能力不足..不会逆向 Java, 懒得学, 鸽了

如果阁下有什么好办法欢迎 PR 🥺👍🏿

**Comment by Jikexiaobai** [comment]
> > 顺便问一下，大佬是否有修复帐密登陆的计划😘
> 
> 曾有两方案但现在都咕咕了
> 
> * ML大法：为了这几十个K的模型的太剧本搞暗恋离谱，想算了
> * 逆向安卓知到APP：能力不足..不会逆向Java，懒得学，鸽了
> 
> 如果有什么好办法欢迎 PR🥺👍🏿

之前用过一个qq框架是Go-cqhttp 留意过里面一个登录方式是浏览器抓取滑条并登录，大佬有空方便看一下吗

**Comment by Jikexiaobai** [comment]
> 直接赋值给属性就可以
> 
> ```
> fucker.cookies = {}
> ```
> 
> 顺便一提这样会自动提取用户的 uuid, 所以赋值不合法的 cookies 会引发异常

直接赋值会报错SyntaxError: invalid decimal literal
![image](https://user-images.githubusercontent.com/49304819/200175673-bdc5f3da-f7ce-48bb-b98b-b1ce685c9411.png)

**Comment by VermiIIi0n** [comment]
那些分号是什么😂, 你的 `dict` 不合 Python 语法啊, 把分号改逗号, 然后键名都用引号围起来.

**Comment by Jikexiaobai** [comment]
ok了，谢谢大佬，不常用py不太清楚😂

**Comment by VermiIIi0n** [comment]
举手之劳, 不用谢~

哈哈, 说起来 go-cqhttp 我也有用, 不过要提取网易验证码那步我尚不清楚怎么做...有时间我再试试吧

**Comment by Jikexiaobai** [comment]
> 举手之劳, 不用谢~
> 
> 哈哈, 说起来 go-cqhttp 我也有用, 不过要提取网易验证码那步我尚不清楚怎么做...有时间我再试试吧

好的，加油大佬，我在尝试使用Go来写一个智慧树刷课和答题的，希望能成功吧😂😂写过网站后端，脚本这种第一次😂
