### ISSUE TITLE
ssl992

### ISSUE THREAD

**Issue by 1837620622** [VermiIIi0n/fuckZHS#42]
<img width="1127" alt="图片" src="https://user-images.githubusercontent.com/35034498/204015121-cb49a0cf-8597-4286-815a-dcf9e6d9bcf5.png">

**Comment by 1837620622** [comment]
以上方法都是用过但是没办法 版本也是对的

**Comment by VermiIIi0n** [comment]
这个证书问题我也没啥有效办法, 如果你用的是Windows的话建议改成用WSL跑
