### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Allencc5658** [VermiIIi0n/fuckZHS#43]
**描述问题**
正确安装之后先是发现运行二维码打不全，然后改成"show_in_terminal": false "ensure_unicode": false二维码以图片的形式，扫码后显示二维码过期要重新扫描

**如何复现**
您遇到问题前进行了什么操作:

1. 把"show_in_terminal"改为false二维码出来了手机扫描显示二维码已过期需要重新扫描

如果可以的话，请附上截图.

**您的操作系统和所使用的本代码版本**
 - OS: MACBOOK PRO 装的虚拟机win7
 - Version: 2.0.2

**错误日志**
这不太清楚

**Comment by VermiIIi0n** [comment]
Windows 下用图片打开总是会让进程卡死, 就算图片显示单独放一个线程里也还是会卡死...

建议直接用 Mac 运行吧

**Comment by Allencc5658** [comment]
后来我试了一下win7如果把跳出来的那个二维码图片先保存到桌面，关掉图片程序就会继续运行直到提示你去扫描二维码，这个时候再去扫的话就会显示已经扫描成功了，可能是程序没运行完出的问题

**Comment by VermiIIi0n** [comment]
就是因为图片显示卡死进程导致没法建立WS连接, 保存为图片确实避开了这点, 直接打印到终端也可以避免卡死.

**Comment by Allencc5658** [comment]
但是我的电脑把show in terminal改为ture二维码只打印一半就比较头疼

**Comment by VermiIIi0n** [comment]
是窗口太小吗? 拉大点应该都能显示. 不然的话还有个endure_unicode可以试试, 不过白底黑字的终端可能会导致扫不出来

**Comment by Allencc5658** [comment]
不是，拉大之后二维码只有半个
