### ISSUE TITLE
二维码每次扫描都是已过期，求大佬解答疑惑[BUG]

### ISSUE THREAD

**Issue by AlanYagn** [VermiIIi0n/fuckZHS#52]
**描述问题**
请详细清晰地描述问题

**如何复现**
您遇到问题前进行了什么操作:
1. 这样
2. 那样
3. 这里
4. 那里

**截图**
如果可以的话，请附上截图.

**您的操作系统和所使用的本代码版本**
 - OS: [e.g. stupid Windows]
 - Version: [e.g. 2.0.2]

**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
最好有 DEBUG 级别日志(使用参数 `-d` 或在配置文件中更改日志等级)

**Comment by VermiIIi0n** [comment]
Windows 自己的问题, 换成打印到终端解决吧, 同样的 issue 已经有了
