### ISSUE TITLE
句柄无效咋回事啊，蜀黍

### ISSUE THREAD

**Issue by yqlm159** [VermiIIi0n/fuckZHS#58]
![Uploading 屏幕截图 2023-03-28 190728.jpg…]()
咋回事啊

**Comment by yqlm159** [comment]
![屏幕截图 2023-03-28 190728](https://user-images.githubusercontent.com/127719539/228217649-6cadacf3-f670-4d37-b36c-227a95aae530.jpg)

**Comment by VermiIIi0n** [comment]
#25
