### ISSUE TITLE
行为修改: 尽可能使用保存的 Cookies 登陆

### ISSUE THREAD

**Issue by VermiIIi0n** [VermiIIi0n/fuckZHS#59]
另外提一个建议，请问能否新增一个自动获取cookie并保留cookie在配置文件里的功能，如果cookie有效则跳过扫码登录，这样很方便调试程序，不然每次修改好测试都要扫码（很容易出现二维码已过期的bug）。 把cookie写死在代码里后续修改会很麻烦。

_Originally posted by @NatsumeOnMars in https://github.com/VermiIIi0n/fuckZHS/discussions/19#discussioncomment-5461109_

**Comment by NatsumeOnMars** [comment]
太牛了，好高效。
