### ISSUE TITLE
[BUG]非首次运行出现"Failed to load course list from file……"

### ISSUE THREAD

**Issue by NatsumeOnMars** [VermiIIi0n/fuckZHS#60]
**描述问题**
运行时出现以下错误：*Failed to load course list from file: Expecting value: line 6 column 1 (char 98)

**如何复现**
您遇到问题前进行了什么操作:
1. 首次运行正常。
2. 第二次以后，100%复现这一问题。

**截图**
![image](https://user-images.githubusercontent.com/96287050/228526812-d632eaa0-5677-4af4-84c4-303c2a1127e9.png)
**您的操作系统和所使用的本代码版本**
 - OS: Win 11
 - Version: 2.5.1

**错误日志**

![image](https://user-images.githubusercontent.com/96287050/228527665-53d09974-14d8-4b1b-b4c8-0e4059cf5445.png)
2023-03-29 19:53:08,757:  created a Fucker 1359310492496, limit: 0, speed: None, end_thre: None
2023-03-29 19:53:08,757:  received cookies: <RequestsCookieJar[]>
2023-03-29 19:53:08,757:  set cookies: <RequestsCookieJar[]>
2023-03-29 19:53:08,758:  proxies: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890', 'ftp': 'http://127.0.0.1:7890'}
2023-03-29 19:53:08,758:  headers: {'Accept': '*/*', 'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"', 'sec-ch-ua-mobile': '?0', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'sec-ch-ua-platform': 'macOS', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-GB,en;q=0.9'}
2023-03-29 19:53:08,758:  received cookies: ******
2023-03-29 19:53:08,759:  POST url: https://onlineservice-api.zhihuishu.com/gateway/t/v1/student/course/share/queryShareCourseInfo
raw_data: {
    "status": 0,
    "pageNo": 1,
    "pageSize": 5,
    "dateFormate": 1680090788000
}
2023-03-29 19:53:08,759:  POST url: https://onlineservice-api.zhihuishu.com/gateway/t/v1/student/course/share/queryShareCourseInfo
data: {
    "secretStr": ******,
    "dateFormate": 1680090788000
}
headers: {
    "Accept": "*/*",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Google Chrome\";v=\"101\"",
    "sec-ch-ua-mobile": "?0",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "sec-ch-ua-platform": "macOS",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-GB,en;q=0.9"
}
cookies: ******
proxies: {
    "http": "http://127.0.0.1:7890",
    "https": "http://127.0.0.1:7890",
    "ftp": "http://127.0.0.1:7890"
}
2023-03-29 19:53:09,014:  {
    "result": {
        "totalCount": 2,
        "courseOpenDtos": [
            {
                "courseId": 1000006736,
                "courseName": "国际私法（华东政法大学）",
                "courseImg": "https://image.zhihuishu.com/zhs/createcourse/course/201710/850460bac50d4feabcab53d867f22ec6.jpg",
                "teacherName": "林燕萍",
                "lessonName": "属人法连接点的新发展",
                "lessonNum": "5.1.3",
                "progress": "32.7%",
                "recruitId": 169820,
                "lessonId": null,
                "courseCount": null,
                "schoolName": "华东政法大学",
                "secret": "4b5e505047594859454a585958435e405e",
                "courseStartTime": 1675785600000,
                "courseEndTime": 1686844799000,
                "status": 0,
                "courseStatus": 2,
                "courseType": 1
            },
            {
                "courseId": 1000008779,
                "courseName": "国际经济法（华东政法大学）",
                "courseImg": "https://image.zhihuishu.com/zhs/createcourse/course/201907/63980ce3bb864e2cb75cb20d8bb2f0ee.jpg",
                "teacherName": "张国元",
                "lessonName": "《联合国国际货物销售合同公约》的适用",
                "lessonNum": "2.1.1",
                "progress": "3.4%",
                "recruitId": 165837,
                "lessonId": null,
                "courseCount": null,
                "schoolName": "华东政法大学",
                "secret": "4b5e5c50465e4859454a5859584d5e4451",
                "courseStartTime": 1675785600000,
                "courseEndTime": 1686844799000,
                "status": 0,
                "courseStatus": 2,
                "courseType": 1
            }
        ]
    },
    "code": 200,
    "message": null,
    "errMsg": null
}
2023-03-29 19:53:09,014:  GET url: https://hikeservice.zhihuishu.com/student/course/aided/getMyCourseList
data: {
    "uuid": "***",
    "data": "2023-03-29T11:53:09.014Z"
}
headers: {
    "Accept": "*/*",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Google Chrome\";v=\"101\"",
    "sec-ch-ua-mobile": "?0",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "sec-ch-ua-platform": "macOS",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-GB,en;q=0.9"
}
cookies: *****
proxies: {
    "http": "http://127.0.0.1:7890",
    "https": "http://127.0.0.1:7890",
    "ftp": "http://127.0.0.1:7890"
}
2023-03-29 19:53:09,151:  {
    "result": {
        "courseList": null,
        "startInngcourseList": [],
        "confirmCourseList": []
    },
    "code": 200,
    "message": null
}

**Comment by VermiIIi0n** [comment]
还有就是文档里提到的 video.videoId 不是 video.id, 还请注意区分 智慧树的数据命名很恶心...

**Comment by NatsumeOnMars** [comment]
震惊，我之前为了获取ID确实在研究这些变量，我还在奇怪为什么不行，原来是命名不一样……
太感谢了！！真的被ZHS恶心到了……

**Comment by VermiIIi0n** [comment]
啊对了, 我翻车了, 之前测试 `cookies` 的方法不太准确, 最好更新下 2.5.2😭
