### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aidangaiguo230331** [VermiIIi0n/fuckZHS#67]
**描述问题**
请详细清晰地描述问题
生成的二维码无法被扫描
**如何复现**
您遇到问题前进行了什么操作:
执行python main.py 

**截图**
如果可以的话，请附上截图.

**您的操作系统和所使用的本代码版本**
 - OS: window
 - Version: 克隆最新版

**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
最好有 DEBUG 级别日志(使用参数 `-d` 或在配置文件中更改日志等级)

**Comment by VermiIIi0n** [comment]
Android端只能识别黑底白码，换终端字体颜色或者改成显示图片
