### ISSUE TITLE
无法显示二维码

### ISSUE THREAD

**Issue by fazheer** [VermiIIi0n/fuckZHS#68]
在Debian11上运行的，环境是python3.10，启动程序后，二维码一直无法显示
![image](https://github.com/VermiIIi0n/fuckZHS/assets/77090621/6a77eb18-1c9e-4447-a268-162af0cd28ab)

**Comment by VermiIIi0n** [comment]
前几个版本根据 #21 修改了默认的二维码显示方式，如果需要在命令行显示二维码的话的话需要把 `config.json` 里的 `show_in_terminal`改成`true`，否则是用图形界面的窗口显示图片。
