### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by zh2250635** [VermiIIi0n/fuckZHS#70]
zhs其实是可以并发的（我用浏览器开十几个窗口同时刷过），可不可以多线程同时开始f***

**Comment by VermiIIi0n** [comment]
啊？是吗！我以前多开tab会报错啊，现在没课了也没法测试，等下学期我看看。

**Comment by zxz1314258** [comment]
二维码刚出来扫描显示过期，这个没法解决，不知道有没有人解决了。windows端的VSC

**Comment by VermiIIi0n** [comment]
> 二维码刚出来扫描显示过期，这个没法解决，不知道有没有人解决了。windows端的VSC

[这里](#25)
