### ISSUE TITLE
没啥给个建议

### ISSUE THREAD

**Issue by DR-lin-eng** [VermiIIi0n/fuckZHS#73]
1.可以重复刷课(主要是后面发现平时分那个10分刷完了才发现)
2添加启动脚本(附代码:
@echo off
cd %~dp0
python main.py -l 25
pause

**Comment by VermiIIi0n** [comment]
好嘞, 但我暂时没课, 等我抓个人抢个账号测试

**Comment by nexplorer-3e** [comment]
同求重复刷课（不仔细看 usage 有 --limit 参数的后果 😭 
忽略 watch_state 写 played_time = 0 会报错：

> Traceback (most recent call last):
>   File "D:\Documents\git\fuckZHS\fucker.py", line 437, in fuckZhidaoCourse
>     self.fuckZhidaoVideo(RAC_id, video.videoId)
>   File "D:\Documents\git\fuckZHS\fucker.py", line 557, in fuckZhidaoVideo
>     self.saveDatabaseIntervalTimeV2(RAC_id,video_id,played_time,last_submit,wp.get(),token_id)
>   File "D:\Documents\git\fuckZHS\fucker.py", line 787, in saveDatabaseIntervalTimeV2
>     return self.zhidaoQuery(record_url, data=data).data
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Documents\git\fuckZHS\fucker.py", line 603, in zhidaoQuery
>     raise e
> Exception: code: -8 msg: 学习总时长下降了

这之后把 last_submit 固定到 video.studyTotalTime 会报：

> Traceback (most recent call last):
>   File "D:\Documents\git\fuckZHS\fucker.py", line 437, in fuckZhidaoCourse
>     self.fuckZhidaoVideo(RAC_id, video.videoId)
>   File "D:\Documents\git\fuckZHS\fucker.py", line 557, in fuckZhidaoVideo
>     self.saveDatabaseIntervalTimeV2(RAC_id,video_id,played_time,last_submit,wp.get(),token_id)
>   File "D:\Documents\git\fuckZHS\fucker.py", line 787, in saveDatabaseIntervalTimeV2
>     return self.zhidaoQuery(record_url, data=data).data
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Documents\git\fuckZHS\fucker.py", line 603, in zhidaoQuery
>     raise e
> Exception: code: -1 msg: 参数解码发生错误

**Comment by VermiIIi0n** [comment]
我下次更新加，不过重复刷没怎么测试过，到时候我先更新到分支里，各位先试试水吧

**Comment by VermiIIi0n** [comment]
已支持重复刷课, 貌似没必要开测试分支
