### ISSUE TITLE
智慧树检测异常

### ISSUE THREAD

**Issue by swaehwdp** [VermiIIi0n/fuckZHS#74]
**描述问题**
在9.29号，私信接收到异常提醒
**如何复现**
您遇到问题前进行了什么操作:
正常操作

**截图**
[截图](http://oss4liview.moji.com/thd_file/2023/10/13/28fc58150130e8921bcfb694a25744e0.jpg)

**您的操作系统和所使用的本代码版本**
 - win10
 - Version: 2.3.8

**错误日志**
运行正常

**Comment by swaehwdp** [comment]
![Uploading IMG20231013121920.jpg…]()

**Comment by VermiIIi0n** [comment]
有试过最新版本吗？

**Comment by swaehwdp** [comment]
没有，但我已经更新最新版了，后面用在检测的话，再来说吧

**Comment by swaehwdp** [comment]
> 有试过最新版本吗？

没有，但我已经更新最新版了，后面用在检测的话，在来问吧

**Comment by CatzMR** [comment]
@VermiIIi0n 我也遇到了被检测的问题 但是没有处罚

**Comment by CatzMR** [comment]
和他截图中的一样

**Comment by swaehwdp** [comment]
> 有试过最新版本吗？

- 昨天试了最新版，今天也弹异常了[http://oss4liview.moji.com/thd_file/2023/10/24/17f7525b2fbf9dff3fa7c5e8ec15a464.jpg](url)

**Comment by swaehwdp** [comment]
> 有试过最新版本吗？

昨天试了最新版的，今天也弹检测异常了[截图](http://oss4liview.moji.com/thd_file/2023/10/24/17f7525b2fbf9dff3fa7c5e8ec15a464.jpg)

**Comment by swaehwdp** [comment]
> > 有试过最新版本吗？
> 
> 昨天试了最新版的，今天也弹检测异常了[截图](http://oss4liview.moji.com/thd_file/2023/10/24/17f7525b2fbf9dff3fa7c5e8ec15a464.jpg)

@VermiIIi0n

**Comment by swaehwdp** [comment]
@VermiIIi0n

**Comment by VermiIIi0n** [comment]
> @VermiIIi0n

好吧, 我有时间研究研究...这个问题之前有issue提到, 但我一直没遇到, 不太好修..

**Comment by VermiIIi0n** [comment]
因为是重复的issue我就先关了吧, 以后更新了我放 #11 里吧
