### ISSUE TITLE
QR 登录验证流程更改

### ISSUE THREAD

**Issue by sniper-Li** [VermiIIi0n/fuckZHS#77]
![image](https://github.com/VermiIIi0n/fuckZHS/assets/88961888/f6a06f7a-4991-475a-a633-27ae7d254879)

**Comment by sniper-Li** [comment]
开debug扫后也没有反应

**Comment by VermiIIi0n** [comment]
QR登录验证流程改了, 刚推送了新版, 但未做太多测试, 欢迎反馈.

**Comment by sniper-Li** [comment]
新版扫码正常了，但是不知道是偶然还是怎们的，第一次扫码登录后，获取到课程自己就停止了，另外可以加个见刷面课的功能吗🤣

**Comment by VermiIIi0n** [comment]
我们学校没见面课所以有点难测试, 加上之前有其他人支持这功能我就没加了. 之后重构代码时候试着加一下吧🫠, 那这issue我就关咯~
