### ISSUE TITLE
被检测

### ISSUE THREAD

**Issue by tomygin** [VermiIIi0n/fuckZHS#78]
昨天我用大佬的脚本把共享课刷完了
```
python main.py -q -s 444
```
今天看，貌似我被ban了
![image](https://github.com/VermiIIi0n/fuckZHS/assets/95734190/0025ab74-b8da-4b11-be4f-dd705a2421ff)
我昨天的刷完的进度是100%，但是今天我的进度被回滚了，突然来了个异常记录，估计被标记了。

我猜是被检测短时间数据变化过大了。
各位道友珍重。

**Comment by VermiIIi0n** [comment]
倍速444不是作死吗😂，第一次见勇士敢这么用，感谢你奉献自己提供的样本。🫡

**Comment by gzp-192** [comment]
请问这个扫二维码的，我的二维码怎么好长。。。

**Comment by gzp-192** [comment]
> > 请问这个扫二维码的，我的二维码怎么好长。。。
> 
> 我猜你是在终端里面展示的二维码，试一试在config.json里面关闭在终端展示，然后就会出现方方正正的二维码了。 ![image](https://user-images.githubusercontent.com/95734190/280715786-a4a0b50f-f08b-4fc5-b451-2da086c45adf.png)

你好，我已经全部关掉了，但还是这个好长的二维码。
![image](https://github.com/VermiIIi0n/fuckZHS/assets/55121150/2e2252ae-0bd3-456b-8f16-a3e2c3081b84)

**Comment by gzp-192** [comment]
> > 请问这个扫二维码的，我的二维码怎么好长。。。
> 
> 我猜你是在终端里面展示的二维码，试一试在config.json里面关闭在终端展示，然后就会出现方方正正的二维码了。 ![image](https://user-images.githubusercontent.com/95734190/280715786-a4a0b50f-f08b-4fc5-b451-2da086c45adf.png)

噢噢，感谢感谢，原来是我改错了地方

**Comment by gzp-192** [comment]
> > 请问这个扫二维码的，我的二维码怎么好长。。。
> 
> 我猜你是在终端里面展示的二维码，试一试在config.json里面关闭在终端展示，然后就会出现方方正正的二维码了。 ![image](https://user-images.githubusercontent.com/95734190/280715786-a4a0b50f-f08b-4fc5-b451-2da086c45adf.png)

不好意思再打扰你一下，请问扫完码后什么反应都没有是什么情况呢？

**Comment by VermiIIi0n** [comment]
stale了, 就先关了
