### ISSUE TITLE
[BUG] 扫码登录之后没反应

### ISSUE THREAD

**Issue by ZHCLN** [VermiIIi0n/fuckZHS#79]
**描述问题**
正常扫码登录，这都可以，跳出来一行*Failed to check update，然后就不动了，Ctrl+C结束程序都结束不了
一般来说运行成功之后，是会有什么提示信息之类的嘛
我尝试了一些参数，发现都是上面这种的

**Comment by VermiIIi0n** [comment]
信息不足，请按issue模版来

**Comment by Mosirin** [comment]
![image](https://github.com/VermiIIi0n/fuckZHS/assets/142426417/531dc448-2d41-4b27-a986-e3bda9e37880)
我扫码以后就提示这个了，怎么解决啊？
