### ISSUE TITLE
[BUG]max函数不支持将float与NoneType比较

### ISSUE THREAD

**Issue by lulu666lulu** [VermiIIi0n/fuckZHS#80]
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    fucker = Fucker(proxies=proxies, speed=args.speed,
  File "fucker.py", line 95, in __init__
    self.end_thre = max(end_thre, 0.0) or 0.91 # video play end threshold, above this will be considered as finished
TypeError: '>' not supported between instances of 'float' and 'NoneType'

**Comment by scris** [comment]
2.6.2 更新后好像现在必须得带 `threshold` 参数了，我试了一下加个 `-t 100` 之后应该可以用

**Comment by VermiIIi0n** [comment]
太丢人了, 速速关issue
