### ISSUE TITLE
登录在刷题过程中失效

### ISSUE THREAD

**Issue by CrazyCatZhang** [VermiIIi0n/fuckZHS#82]
**描述问题**
刷题刷了一段时间之后就提示要未登录

**如何复现**
您遇到问题前进行了什么操作:
1. python main.py

**截图**
![image](https://github.com/VermiIIi0n/fuckZHS/assets/67346540/d3a3142b-ac53-41fb-b162-f48b7ae6e8ce)

**您的操作系统和所使用的本代码版本**
 - OS: macos Sonoma 14.0
 - Version: 2.6.1

**错误日志**
2023-11-18 01:03:20,377:  code: 403 msg: 未登录啊

**Comment by VermiIIi0n** [comment]
有debug日志吗？我这不能复现。
