### ISSUE TITLE
运行生成的二维码太大了

### ISSUE THREAD

**Issue by xym520520** [VermiIIi0n/fuckZHS#83]
![IMG_20231120_142555.jpg](https://github.com/VermiIIi0n/fuckZHS/assets/129748544/09859c20-7be5-4d5b-8ca1-7c778fba2efc)

**Comment by xym520520** [comment]
![IMG_20231120_142555.jpg](https://github.com/VermiIIi0n/fuckZHS/assets/129748544/b728fcca-8dfb-4995-b9f1-32e372fb8b1b)

**Comment by xym520520** [comment]
已经把他拉到最大了，还是有一部分显示不出来

**Comment by zx2023qj** [comment]
修改pycharm控制台的行高

> 已经把他拉到最大了，还是有一部分显示不出来

**Comment by Sorrow-Scarlet** [comment]
建议用windows terminal, 或者你试试cmd能不能直接ctrl+滚轮缩放，terminal能缩放，所以扫到了
