### ISSUE TITLE
Captcha Required

### ISSUE THREAD

**Issue by FatPigJ** [VermiIIi0n/fuckZHS#84]
自动闪退
error log：
2023-11-21 13:51:04,120:  captcha required

**Comment by Groos-dev** [comment]
这个估计在问题估计在后端不太好解决，如果非要全程挂机可以去尝试一下油糇脚本

**Comment by VermiIIi0n** [comment]
加验证码过于麻烦了，以后改用App的接口可以解决，但我不会逆向所以咕咕了。
