### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by cqep** [VermiIIi0n/fuckZHS#86]
这个配置有点复杂 能不能简化一下 对于小白；来说有点复杂

**Comment by VermiIIi0n** [comment]
配置是指配置文件还是配置环境？

配置文件不是必要的，直接运行也完全没问题；配置环境的话只需要 Store 里下载 Python，GitHub 下载这个 repo，一句指令安装依赖，最后运行就行，也就四步。

不过也许之后会考虑打个包方便一键运行吧。

**Comment by cqep** [comment]
> 配置是指配置文件还是配置环境？
> 
> 配置文件不是必要的，直接运行也完全没问题；配置环境的话只需要 Store 里下载 Python，GitHub 下载这个 repo，一句指令安装依赖，最后运行就行，也就四步。
> 
> 不过也许之后会考虑打个包方便一键运行吧。

大佬，后面还是打个包吧 方便一键运行
