### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cqep** [VermiIIi0n/fuckZHS#87]
能不能加入使用 账号密码登录 这个功能呢

**Comment by VermiIIi0n** [comment]
这个问题多次提起了哈哈，不过我一直咕，主要是走网页API绕不过人机验证，就算可以维护成本也太高了；走App接口又不会逆向。总之是在日程里的，就是得再花点时间，骚瑞了。

**Comment by cqep** [comment]
加油加油 我相信大佬

**Comment by VermiIIi0n** [comment]
那我先关下这 issue 了，之前已经有类似的了。
