### ISSUE TITLE
“报错: [WinError 6] 句柄无效”可能的解决方案

### ISSUE THREAD

**Issue by common5** [VermiIIi0n/fuckZHS#93]
通过查看日志发现，报错位置在fucker.py第426行：w_lim = os.get_terminal_size().columns - 1 # width limit for terminal output
可以考虑在fucker.py中`import shutil`
并将`w_lim = os.get_terminal_size().columns - 1`全局替换为`w_lim = shutil.get_terminal_size().columns - 1`，猜测报错的可能原因是因为我是在pycharm里运行的代码，导致没法正常获取终端宽度（？）

**Comment by VermiIIi0n** [comment]
好勒，感谢建议，没想到还有个漏掉的 `os.get_terminal_size`, 我还以为已经修好了，之后我会更新的。
