### ISSUE TITLE
[BUG] GNOME 特定主题无法显示二维码

### ISSUE THREAD

**Issue by lantianmyx** [VermiIIi0n/fuckZHS#97]
![image](https://github.com/user-attachments/assets/3b728869-4cd4-4fb4-81f6-c392b8f76313)
用的Ubuntu 一直不出二维码 网上查了一些方法 还是出不来

**Comment by VermiIIi0n** [comment]
我无法在ubuntu上复现, 看报错的话是gnome主题的问题, 可以试试`sudo apt install adwaita-icon-theme-full`, 另外有试过不同的二维码显示方式吗, 上次PR里更新了保存至文件的选项, 虽然麻烦点但应该可以解决你的问题
